#!/usr/bin/env bash
echo "****************"
echo "Before running this, download the latest Kicad nightly and mount the dmg"
echo "https://kicad-downloads.s3.cern.ch/index.html?prefix=osx/nightly/"
echo "This script currently does not support the unified dmg or the extras dmg, so make sure to download the nightly."
echo "This script will do the following:"
echo " - Copy the files off of the disk image into /Applications/KiCad/ and /Library/Application Support/kicad/"
echo "   -- If you have a folder called packages3d inside /Library/Application Support/kicad/modules/"
echo "      then the script will keep that folder but overwrite everything else in /Library/Application Support/kicad/modules/"
echo " - Pull out any lines containing \"4ms\" in the current fp/sym-lib-table files and merge these lines into the new installation's fp/sym-lib-table"
echo " - Install the merged fp-lib-table and sym-lib-table";
echo "   -- All kicad libraries will be disabled"
echo ""
echo "Ready? Make sure KiCad is not running and the KiCad dmg is mounted."
echo ""

read -n1 -rsp "Press space to continue or any other key to cancel" key
if [ "$key" = '' ]; then
	echo ""
	echo "Copying KiCad app..."
	cp -r /Volumes/KiCad/KiCad /Applications

	echo ""
	echo "Copying kicad/template into Application Support/kicad..."
	cp -r /Volumes/KiCad/kicad/template /Library/Application\ Support/kicad/

	echo ""
	echo "Copying kicad/library into Application Support/kicad..."
	cp -r /Volumes/KiCad/kicad/library /Library/Application\ Support/kicad/

	echo ""
	echo "Copying kicad/share into Application Support/kicad..."
	cp -r /Volumes/KiCad/kicad/share /Library/Application\ Support/kicad/

	echo ""
	echo "Copying kicad/help into Application Support/kicad..."
	cp -r /Volumes/KiCad/kicad/help /Library/Application\ Support/kicad/

	echo ""
	echo "Moving packages3d out of the way..."
	mv /Library/Application\ Support/kicad/modules/packages3d /Library/Application\ Support/kicad/packages3d

	echo ""
	echo "Copying kicad/modules into Application Support/kicad..."
	cp -r /Volumes/KiCad/kicad/modules /Library/Application\ Support/kicad/

	echo ""
	echo "Moving packages3d back into modules/..."
	mv /Library/Application\ Support/kicad/packages3d /Library/Application\ Support/kicad/modules/packages3d

	cd ~/Library/Preferences/kicad

	#Backup the old tables
	echo ""
	echo "Backing up the existing fp-lib-table and sym-lib-table as fp-lib-table.bak and sym-lib-table.bak"
	cp fp-lib-table fp-lib-table.bak
	cp sym-lib-table sym-lib-table.bak

	#Copy the lib tables to the User directory
	echo ""
	echo "Copying the new fp-lib-table and sym-lib-table files into ~/Library/Preferences/kicad/"
	cp /Library/Application\ Support/kicad/template/fp-lib-table ~/Library/Preferences/kicad/fp-lib-table-new
	cp /Library/Application\ Support/kicad/template/sym-lib-table ~/Library/Preferences/kicad/sym-lib-table-new

	#Extract the 4ms libs 
	echo ""
	echo "Extracting all lines containing '4ms' from the existing lib-tables"
	cat fp-lib-table | grep 4ms > fp-lib-table-4ms
	cat sym-lib-table | grep 4ms > sym-lib-table-4ms

	#Disable all kicad libraries (we only want the 4ms libraries enabled)
	echo ""
	echo "Disabling all kicad official libraries"
	sed 's/))$/)(disabled))/' fp-lib-table-new > fp-lib-table-tmp
	sed 's/))$/)(disabled))/' sym-lib-table-new > sym-lib-table-tmp

	#Merge the 4ms library lines after the first line --- first line starts with '(fp_lib_table'
	echo ""
	echo "Merging the 4ms library lines and the new fp-lib-table"
	rm fp-lib-table
	sed -e '/(fp_lib_table/rfp-lib-table-4ms' fp-lib-table-tmp > fp-lib-table

	#Merge the 4ms library lines after the first line --- first line starts with '(sym_lib_table'
	echo ""
	echo "Merging the 4ms library lines and the new sym-lib-table"
	rm sym-lib-table
	sed -e '/(sym_lib_table/rsym-lib-table-4ms' sym-lib-table-tmp > sym-lib-table

	#Display difference in tables
	echo ""
	echo "Difference between old and new fp-lib-table:"
	diff fp-lib-table fp-lib-table.bak

	echo ""
	echo "Difference between old and new sym-lib-table:"
	diff sym-lib-table sym-lib-table.bak

	echo ""
	echo "Done!"
	echo ""
else
	echo ""
	echo "Canceled."
fi
